name: game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  flame_tiled: ^3.0.7
  #just_audio: ^0.9.35
  flame_audio: ^2.11.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
    
  assets:
    - assets/tiles/Level-01.tmx
    - assets/tiles/Level-02.tmx
    - assets/tiles/Menu.tmx 
    - assets/tiles/pixel adventure.tsx
    - assets/tiles/
    - assets/images/
    - assets/audio/
    - assets/images/Terrain/
    - assets/images/Background/
    - assets/images/Items/Fruits/
    - assets/images/Traps/Saw/
    - assets/images/Joystick components/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/
    - assets/images/Enemies/Chicken/
    - assets/images/Terrain/Terrain (16x16).png
    - assets/images/Items/Checkpoints/Checkpoint/

